/**
 * Phase 1.5 shared helpers — reads Agent 2's on-chain content from the repo's asset
 * files and shapes it for upload, EXACTLY mirroring the in-test fixture
 * (test/utils/RendererAssets.sol, generated by tools/gen_assets_sol.py) and the
 * provenance arrangement (assets/assignments.json, from tools/assign_traits.py).
 *
 * "What is tested is what ships": the byte transforms here (UTF-8 fragments, the
 * honors inter-tag whitespace collapse, the assignments → WordData mapping) match
 * the generators one-for-one, so the uploaded bytes equal the snapshot-tested ones.
 */
import * as fs from "fs";
import * as path from "path";
import {ethers, keccak256} from "ethers";

export const ASSETS_DIR = path.join(__dirname, "..", "..", "assets");
const ASSIGNMENTS_PATH = path.join(ASSETS_DIR, "assignments.json");
const FONT_CHUNKS_PATH = path.join(ASSETS_DIR, "font", "font_chunks.json");
const MATERIALS_PATH = path.join(ASSETS_DIR, "traits", "materials.json");
const HONORS_DIR = path.join(ASSETS_DIR, "honors");
const HONORS_MANIFEST_PATH = path.join(HONORS_DIR, "manifest.json");

export const TOTAL_SLOTS = 10_000;

/** Category enum order — FROZEN in Types.sol (NOUN, VERB, ADJ, ADV). Never reorder. */
export const CATEGORY_INDEX: Record<string, number> = {NOUN: 0, VERB: 1, ADJ: 2, ADV: 3};

/** One WordBank slot, in the frozen Types.sol struct field order. */
export interface WordData {
  word: string;
  category: number;
  material: number;
  ink: number;
  background: number;
  honors: boolean;
}

export interface Arrangement {
  words: WordData[];
  /** keccak256 of the exact assignments.json bytes — the public snipe-proof commitment. */
  provenanceHash: string;
}

/**
 * The shuffled provenance arrangement: slot i ← assignments[i]. The provenance hash is
 * keccak256 over the EXACT file bytes of assets/assignments.json (the same payload
 * tools/assign_traits.py hashes and prints) — reproducible by anyone from the public file:
 *   keccak256(readFileSync("assets/assignments.json"))
 */
export function loadArrangement(): Arrangement {
  const raw = fs.readFileSync(ASSIGNMENTS_PATH); // exact bytes — do NOT re-serialize
  const provenanceHash = keccak256(new Uint8Array(raw));
  const parsed = JSON.parse(raw.toString("utf8")) as {assignments: any[]};
  const a = parsed.assignments;
  if (a.length !== TOTAL_SLOTS) throw new Error(`assignments.json has ${a.length} entries, expected ${TOTAL_SLOTS}`);

  const words: WordData[] = a.map((e, i) => {
    const category = CATEGORY_INDEX[e.category];
    if (category === undefined) throw new Error(`slot ${i}: unknown category ${e.category}`);
    if (!e.word || typeof e.word !== "string") throw new Error(`slot ${i}: empty/invalid word`);
    return {
      word: e.word,
      category,
      material: e.material,
      ink: e.ink,
      background: e.background,
      honors: !!e.honors,
    };
  });
  return {words, provenanceHash};
}

/** Font: the subsetted WOFF2 split into SSTORE2 chunks (hex strings, "0x…"). */
export function loadFontChunks(): string[] {
  const d = JSON.parse(fs.readFileSync(FONT_CHUNKS_PATH, "utf8")) as {chunks: string[]};
  if (!d.chunks?.length) throw new Error("font_chunks.json has no chunks");
  return d.chunks;
}

export interface MaterialUpload {
  name: string;
  tier: number;
  safeWidth: number;
  fragment: Uint8Array; // UTF-8 bytes of the <g>…</g> fragment
  inks: [string, string][]; // [name, color]
  backgrounds: [string, string][]; // [name, color]
}

/** Materials: one reusable SVG fragment + the validInks/validBackgrounds tables, per surface. */
export function loadMaterials(): MaterialUpload[] {
  const mats = (JSON.parse(fs.readFileSync(MATERIALS_PATH, "utf8")) as {materials: any[]}).materials;
  return mats.map((m) => {
    const frag: string = m.fragment;
    if (!frag.startsWith("<g") || !frag.endsWith("</g>") || frag.includes('"') || frag.includes("\n")) {
      throw new Error(`material ${m.name}: fragment not a single-line <g>…</g> without double quotes`);
    }
    return {
      name: m.name,
      tier: m.tier,
      safeWidth: m.safeWidth,
      fragment: ethers.toUtf8Bytes(frag),
      inks: m.inks.map((k: any) => [k.name, k.color] as [string, string]),
      backgrounds: m.backgrounds.map((b: any) => [b.name, b.color] as [string, string]),
    };
  });
}

export interface HonorsUpload {
  word: string;
  art: Uint8Array; // UTF-8 bytes of the bespoke <g>…</g> artwork
}

/**
 * Honors 1/1 artworks, keyed by their stored (capitalized) word. The transform mirrors
 * tools/gen_assets_sol.py exactly: read the .svg, .trim(), then collapse inter-tag
 * whitespace (>\s+< → ><) so the uploaded bytes equal the snapshot-tested art.
 */
export function loadHonors(): HonorsUpload[] {
  const manifest = JSON.parse(fs.readFileSync(HONORS_MANIFEST_PATH, "utf8")) as Record<string, {file: string}>;
  return Object.entries(manifest).map(([word, entry]) => {
    const svg = fs.readFileSync(path.join(HONORS_DIR, entry.file), "utf8").trim().replace(/>\s+</g, "><");
    if (!svg.startsWith("<g") || !svg.endsWith("</g>") || svg.includes('"')) {
      throw new Error(`honors ${word}: art not a single-line <g>…</g> without double quotes`);
    }
    return {word, art: ethers.toUtf8Bytes(svg)};
  });
}

/** Fails loudly unless the broadcaster is the on-chain authority for an owner-only call. */
export function requireAuthority(signerAddr: string, onchainAuthority: string, label: string): void {
  if (ethers.getAddress(signerAddr) !== ethers.getAddress(onchainAuthority)) {
    throw new Error(
      `broadcaster ${signerAddr} is not the ${label} (${onchainAuthority}). ` +
        `Phase 1.5 calls are owner-only — run with the ADMIN key (the same key that ran Phase 1).`,
    );
  }
}
