#!/usr/bin/env python3
"""Bakes the numerals 0-9 and '#' from Fraunces into baked SVG outline paths.

WHY THIS EXISTS: the onchain WB font subset is A-Z + a-z only (the word list is
lowercase letters; honors are capitalized) — it has NO digits or punctuation.
The pre-reveal `unrevealedTokenURI(tokenId)` must draw `WORDBANK #<id>`, so the
id numerals (and the '#') are baked here from Fraunces — the SAME typeface, same
instance the WB subset pins (opsz 144, wght 564, SOFT 0, WONK 1) — into vector
paths embedded directly in `src/libraries/Numerals.sol`. No font dependency, no
per-token state: each digit is identical art; only WHICH digits a token shows
varies, and the id reveals nothing about the eventual word/traits.

Coordinate system of the emitted paths: final display pixels, y-DOWN, each
glyph's pen origin at x=0 and baseline at y=0 (natural side bearings kept inside
the path, advance kept separately) — so the Renderer lays a number out by pure
integer pen-advance translation, no scaling math onchain.

Run:  python tools/font/build_numerals.py
"""

from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "assets" / "font" / "Fraunces-VF.ttf"
OUT_SOL = ROOT / "src" / "libraries" / "Numerals.sol"

# Same instance the WB subset pins (assets/traits/README.md → Typeface).
INSTANCE = {"opsz": 144, "wght": 564, "SOFT": 0, "WONK": 1}

# Display font-size in px on the 1000x1000 canvas. Fraunces cap height is
# 0.70 em, so SIZE 88 → ~62px caps: a quiet identity line, not a headline.
SIZE = 88

GLYPHS = "0123456789#"


def bake() -> tuple[dict[str, str], dict[str, int]]:
    font = TTFont(SRC)
    instantiateVariableFont(font, INSTANCE, inplace=True)
    glyphset = font.getGlyphSet()
    cmap = font.getBestCmap()
    upem = font["head"].unitsPerEm
    scale = SIZE / upem

    paths: dict[str, str] = {}
    advances: dict[str, int] = {}
    for ch in GLYPHS:
        gname = cmap[ord(ch)]
        # Integer coordinates: at this display size (~62px caps on a 1000px
        # canvas) sub-pixel precision is invisible, and dropping the decimals
        # roughly halves the baked bytecode — worth it for the contract-size
        # budget (the paths live inline in the Renderer's bytecode).
        pen = SVGPathPen(glyphset, ntos=lambda v: format(round(v)))
        # (scale, 0, 0, -scale, 0, 0): font units (y-up) -> display px (y-down),
        # baseline at y=0, pen origin at x=0.
        glyphset[gname].draw(TransformPen(pen, (scale, 0, 0, -scale, 0, 0)))
        d = pen.getCommands()
        if '"' in d or "\n" in d:
            raise SystemExit(f"{ch}: bad path chars")
        key = "hash" if ch == "#" else ch
        paths[key] = d
        advances[key] = round(glyphset[gname].width * scale)
    return paths, advances


def emit_solidity(paths: dict[str, str], advances: dict[str, int]) -> None:
    digits = [str(i) for i in range(10)]
    lines = [
        "// SPDX-License-Identifier: MIT",
        "pragma solidity ^0.8.26;",
        "",
        "// AUTO-GENERATED by tools/font/build_numerals.py - DO NOT EDIT BY HAND.",
        "// Baked outlines of 0-9 and '#' from Fraunces (opsz 144, wght 564, SOFT 0,",
        "// WONK 1) - the same face/instance as the onchain WB font subset, which",
        "// itself carries no digits. Used only by Renderer.unrevealedTokenURI to draw",
        "// the per-token id on the pre-reveal placeholder. Coordinates are display px,",
        f"// y-down, baseline at y=0, pen origin at x=0; glyph size {SIZE}px.",
        "library Numerals {",
        f"    /// @notice Display font-size (px) the outlines were baked at.",
        f"    uint256 internal constant SIZE = {SIZE};",
        "",
        "    /// @notice Pen advance (px) for digit `d` (0-9).",
        "    function advance(uint256 d) internal pure returns (uint256) {",
        "        uint16[10] memory a = [",
        "            uint16(" + str(advances["0"]) + "), " + ", ".join(str(advances[d]) for d in digits[1:]),
        "        ];",
        "        return a[d];",
        "    }",
        "",
        "    /// @notice Pen advance (px) for the '#' glyph.",
        f"    function hashAdvance() internal pure returns (uint256) {{ return {advances['hash']}; }}",
        "",
        "    /// @notice Baked outline `d` for digit `d` (0-9), pen origin x=0, baseline y=0.",
        "    function path(uint256 d) internal pure returns (string memory) {",
    ]
    for i, dig in enumerate(digits):
        cond = "if" if i == 0 else "else if"
        lines.append(f"        {cond} (d == {dig}) return \"{paths[dig]}\";")
    lines += [
        '        return "";',
        "    }",
        "",
        "    /// @notice Baked outline `d` for the '#' glyph, pen origin x=0, baseline y=0.",
        f'    function hashPath() internal pure returns (string memory) {{ return "{paths["hash"]}"; }}',
        "}",
        "",
    ]
    OUT_SOL.parent.mkdir(parents=True, exist_ok=True)
    OUT_SOL.write_text("\n".join(lines), encoding="utf-8")
    total = sum(len(p) for p in paths.values())
    print(f"wrote {OUT_SOL.relative_to(ROOT)} ({len(paths)} glyphs, {total} path bytes, size {SIZE}px)")
    print("advances:", advances)


if __name__ == "__main__":
    p, a = bake()
    emit_solidity(p, a)
