#!/usr/bin/env python3
"""Generates test/utils/RendererAssets.sol from the asset sources.

Single source of truth flow:
  assets/font/font_chunks.json   (from tools/font/subset_font.py)
  assets/traits/materials.json   (hand-curated tables + fragments)
  assets/honors/manifest.json    (word -> svg file, optional until honors land)
        |
        v
  test/utils/RendererAssets.sol  (library that loads + seals a Renderer)

Tests and the deploy flow replay the exact same loader calls, so what is
tested is what ships. Fragments MUST be single-line and use only
single-quoted attributes (validated here) so they embed in Solidity strings.

Run:  python tools/gen_assets_sol.py
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FONT_CHUNKS = ROOT / "assets" / "font" / "font_chunks.json"
MATERIALS = ROOT / "assets" / "traits" / "materials.json"
HONORS_MANIFEST = ROOT / "assets" / "honors" / "manifest.json"
OUT = ROOT / "test" / "utils" / "RendererAssets.sol"


def check_fragment(name: str, frag: str) -> str:
    if "\n" in frag or "\r" in frag:
        raise SystemExit(f"{name}: fragment must be single-line")
    if '"' in frag or "\\" in frag:
        raise SystemExit(f"{name}: fragment must not contain double quotes or backslashes")
    if not frag.startswith("<g") or not frag.endswith("</g>"):
        raise SystemExit(f"{name}: fragment must be a <g>...</g> group")
    if not all(31 < ord(c) < 127 for c in frag):
        raise SystemExit(f"{name}: fragment must be printable ASCII")
    return frag


def main() -> None:
    font = json.loads(FONT_CHUNKS.read_text())
    mats = json.loads(MATERIALS.read_text())["materials"]
    honors = {}
    if HONORS_MANIFEST.exists():
        manifest = json.loads(HONORS_MANIFEST.read_text())
        for word, entry in manifest.items():
            art = (ROOT / "assets" / "honors" / entry["file"]).read_text().strip()
            art = re.sub(r">\s+<", "><", art)  # collapse inter-tag whitespace
            honors[word] = (check_fragment(f"honors:{word}", art), entry)

    lines = [
        "// SPDX-License-Identifier: MIT",
        "pragma solidity ^0.8.26;",
        "",
        "// AUTO-GENERATED by tools/gen_assets_sol.py — DO NOT EDIT BY HAND.",
        "// Regenerate after changing assets/font, assets/traits, or assets/honors.",
        "",
        'import {Renderer} from "../../src/Renderer.sol";',
        "",
        "library RendererAssets {",
        "    /// @dev Curated surface for each honors 1/1 (consumed by previews and the",
        "    ///      trait-assignment tool; honors surfaces are curated, never random).",
        "    struct HonorsEntry {",
        "        string word;",
        "        uint8 category; // Category enum index (0 NOUN, 1 VERB, 2 ADJ, 3 ADV)",
        "        uint8 material;",
        "        uint8 background;",
        "    }",
        "",
        "    function loadFont(Renderer r) internal {",
        f"        bytes[] memory chunks = new bytes[]({len(font['chunks'])});",
    ]
    for i, c in enumerate(font["chunks"]):
        lines.append(f'        chunks[{i}] = hex"{c[2:]}";')
    lines += [
        "        r.addFontChunks(chunks);",
        "    }",
        "",
        "    function loadMaterials(Renderer r) internal {",
    ]
    for m in mats:
        frag = check_fragment(m["name"], m["fragment"])
        lines.append("        {")
        lines.append(f"            Renderer.Ink[] memory inks = new Renderer.Ink[]({len(m['inks'])});")
        for i, ink in enumerate(m["inks"]):
            lines.append(f'            inks[{i}] = Renderer.Ink("{ink["name"]}", "{ink["color"]}");')
        lines.append(
            f"            Renderer.Background[] memory bgs = new Renderer.Background[]({len(m['backgrounds'])});"
        )
        for i, bg in enumerate(m["backgrounds"]):
            lines.append(f'            bgs[{i}] = Renderer.Background("{bg["name"]}", "{bg["color"]}");')
        lines.append(
            f'            r.addMaterial("{m["name"]}", {m["tier"]}, {m["safeWidth"]}, bytes("{frag}"), inks, bgs);'
        )
        lines.append("        }")
    lines += [
        "    }",
        "",
        "    function loadHonors(Renderer r) internal {",
    ]
    if honors:
        for word, (art, _) in honors.items():
            lines.append(f'        r.addHonorsArt("{word}", bytes("{art}"));')
    else:
        lines.append("        // No honors artworks generated yet.")
        lines.append("        r; // silence unused warning")
    lines += [
        "    }",
        "",
        "    function honorsList() internal pure returns (HonorsEntry[] memory list) {",
        f"        list = new HonorsEntry[]({len(honors)});",
    ]
    for i, (word, (_, entry)) in enumerate(honors.items()):
        lines.append(
            f'        list[{i}] = HonorsEntry("{word}", {entry["category"]}, {entry["material"]}, {entry["background"]});'
        )
    lines += [
        "    }",
        "",
        "    function loadAll(Renderer r) internal {",
        "        loadFont(r);",
        "        loadMaterials(r);",
        "        loadHonors(r);",
        "        r.seal();",
        "    }",
        "}",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(mats)} materials, {len(honors)} honors, {len(font['chunks'])} font chunks)")


if __name__ == "__main__":
    main()
