/**
 * ABI sync — Foundry is the compiler of record (root AGENTS.md). This script
 * is the ONLY way ABIs enter the dApp: it reads the forge artifacts under
 * `../../out` and emits typed `as const` ABI modules into
 * `lib/contracts/abis/`. ABIs are NEVER hand-copied.
 *
 * Run from `app/`:  npm run sync:abis
 * Re-run after any `forge build` that changes a contract's external surface.
 *
 * Node 23.6+/24 runs this directly via type-stripping (`node scripts/...ts`).
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(HERE, "..", "..", "out");
const ABI_DIR = path.resolve(HERE, "..", "lib", "contracts", "abis");

/**
 * The contracts the dApp reads/writes. `file` is the .sol dir under out/,
 * `name` the artifact (and the JSON file basename), `exportName` the camelCase
 * `<x>Abi` symbol the app imports. Our nine protocol contracts only — the
 * canonical Uniswap ABIs for the swap surface come from the @uniswap SDKs and
 * a small curated set (see lib/contracts/uniswap), not from our out/.
 */
interface Entry {
  file: string;
  name: string;
  exportName: string;
}

const MANIFEST: Entry[] = [
  { file: "WordToken.sol", name: "WordToken", exportName: "wordTokenAbi" },
  { file: "WordBank.sol", name: "WordBank", exportName: "wordBankAbi" },
  { file: "Renderer.sol", name: "Renderer", exportName: "rendererAbi" },
  { file: "RewardsDistributor.sol", name: "RewardsDistributor", exportName: "rewardsDistributorAbi" },
  { file: "BountyEngine.sol", name: "BountyEngine", exportName: "bountyEngineAbi" },
  { file: "BurnEngine.sol", name: "BurnEngine", exportName: "burnEngineAbi" },
  { file: "FeeHook.sol", name: "FeeHook", exportName: "feeHookAbi" },
  { file: "LPLocker.sol", name: "LPLocker", exportName: "lpLockerAbi" },
  { file: "RoyaltySplitter.sol", name: "RoyaltySplitter", exportName: "royaltySplitterAbi" },
  // ── WORD v2 relaunch ──
  { file: "WordTokenV2.sol", name: "WordTokenV2", exportName: "wordTokenV2Abi" },
  { file: "WordStaking.sol", name: "WordStaking", exportName: "wordStakingAbi" },
  { file: "WordMigrator.sol", name: "WordMigrator", exportName: "wordMigratorAbi" },
  { file: "FeeHookV2.sol", name: "FeeHookV2", exportName: "feeHookV2Abi" },
];

type AbiItem = Record<string, unknown>;

function loadAbi(entry: Entry): AbiItem[] {
  const p = path.join(OUT_DIR, entry.file, `${entry.name}.json`);
  if (!fs.existsSync(p)) {
    throw new Error(
      `Missing forge artifact ${p} — run \`forge build\` at the repo root first.`,
    );
  }
  const artifact = JSON.parse(fs.readFileSync(p, "utf8")) as { abi?: AbiItem[] };
  if (!Array.isArray(artifact.abi)) {
    throw new Error(`Artifact ${p} has no abi array.`);
  }
  return artifact.abi;
}

function emit(entry: Entry, abi: AbiItem[]): string {
  const banner =
    `// GENERATED by scripts/sync-abis.ts from out/${entry.file}/${entry.name}.json — DO NOT EDIT.\n` +
    `// Re-run \`npm run sync:abis\` after \`forge build\`.\n`;
  return `${banner}export const ${entry.exportName} = ${JSON.stringify(abi)} as const;\n`;
}

function main(): void {
  fs.mkdirSync(ABI_DIR, { recursive: true });
  const indexLines: string[] = [
    "// GENERATED by scripts/sync-abis.ts — DO NOT EDIT.\n",
  ];
  let count = 0;
  for (const entry of MANIFEST) {
    const abi = loadAbi(entry);
    const fileName = `${entry.name}.ts`;
    fs.writeFileSync(path.join(ABI_DIR, fileName), emit(entry, abi), "utf8");
    indexLines.push(`export { ${entry.exportName} } from "./${entry.name}";`);
    count += 1;
  }
  fs.writeFileSync(path.join(ABI_DIR, "index.ts"), indexLines.join("\n") + "\n", "utf8");
  console.log(`sync-abis: wrote ${count} ABIs + index.ts to lib/contracts/abis/`);
}

main();
